import { strToU8, zipSync } from 'fflate';
import {
  fileForContentTypes,
  FileForRelThumbnail,
  to3dmodelSimple,
} from '@jscadui/3mf-export';
import type { MeshData } from './types';

const IDENTITY_TRANSFORM = [
  1, 0, 0, 0,
  0, 1, 0, 0,
  0, 0, 1, 0,
  0, 0, 0, 1,
] as const;

/**
 * Pack a mesh into a binary 3MF (zipped XML) ArrayBuffer. 3MF preserves
 * topology guarantees (no lossy STL re-import), and is the format slicers
 * expect for multi-material / multi-color models.
 */
export function meshTo3mf(mesh: MeshData, modelName = 'Gridsmith'): ArrayBuffer {
  const rels = new FileForRelThumbnail();
  rels.add3dModel('3D/3dmodel.model');

  const modelXml = to3dmodelSimple(
    [
      {
        id: '1',
        name: modelName,
        vertices: mesh.vertices,
        indices: mesh.indices,
        transform: [...IDENTITY_TRANSFORM] as unknown as number[],
      },
    ],
    {
      unit: 'millimeter',
      title: modelName,
      description: `${modelName} — generated by Gridsmith`,
      application: 'Gridsmith',
    },
    7,
  );

  const zip = zipSync(
    {
      [fileForContentTypes.name]: strToU8(fileForContentTypes.content),
      [rels.name]: strToU8(rels.content),
      '3D/3dmodel.model': strToU8(modelXml),
    },
    { level: 6 },
  );

  return zip.buffer.slice(zip.byteOffset, zip.byteOffset + zip.byteLength) as ArrayBuffer;
}
